#!/bin/bash

function main {
	local actual=`cat /sys/class/backlight/intel_backlight/actual_brightness`
	local command=${1}
	local max=`cat /sys/class/backlight/intel_backlight/max_brightness`

	local delta=$(((max / 10) + (max % 10 > 0)))

	if [ ${command} == "down" ]
	then
		actual=$((actual - delta));
	else
		actual=$((actual + delta));
	fi

	if [ ${actual} -gt ${max} ]
	then
		actual=${max}
	elif [ ${actual} -lt 0 ]
	then
		actual=1
	fi

	echo ${actual} > /sys/class/backlight/intel_backlight/brightness
}

main ${1}