#!/bin/sh

function prepare_branch {
	if [ ! -e "${1}/app.server.${USER}.properties" ]
	then
		echo "app.server.parent.dir=/home/me/dev/bundles/${2}" > ${1}/app.server.${USER}.properties

		pushd ${1}

		#ant -Dmirrors.hostname= setup-libs

		ant -f build-dist.xml unzip-tomcat

		#ant -f build-test.xml setup-testable-tomcat

		popd
	fi
}

function prepare_work_dir {
	local branch=${2}
	local repository=${1}

	local work_dir=${repository//-ee/}

	work_dir=~/dev/projects/${work_dir}-${branch}

	if [ ! -e ${work_dir} ] ||
	   [ ! -e ${work_dir}/.git ]
	then
		rm -fr ${work_dir}

		echo ""
		echo "git new-workdir ~/dev/projects/${repository} ${work_dir} ${branch}"
		echo ""

		git new-workdir ~/dev/projects/${repository} ${work_dir} ${branch}
	fi

	local repository_dir=${work_dir}

	if [ ${branch} == "master" ]
	then
		repository_dir=~/dev/projects/${repository}
	fi

	mkdir -p ${repository_dir}

	if [[ ${branch} != *-private ]]
	then
		prepare_branch ${repository_dir} ${branch}
	fi
}

prepare_branch ~/dev/projects/liferay-portal master

prepare_work_dir liferay-portal-ee 7.0.x
prepare_work_dir liferay-portal-ee 7.0.x-private
prepare_work_dir liferay-portal-ee 7.1.x
prepare_work_dir liferay-portal-ee 7.1.x-private
prepare_work_dir liferay-portal-ee 7.2.x
prepare_work_dir liferay-portal-ee 7.2.x-private
prepare_work_dir liferay-portal-ee 7.3.x
prepare_work_dir liferay-portal-ee 7.3.x-private
prepare_work_dir liferay-portal-ee master-private