#!/bin/bash

function set_property {
	local deviceIds=$(xinput --list | grep "Logitech MX518\|Logitech USB Receiver" | sed -n 's/.*id=\([0-9]\+\).*/\1/p')

	for deviceId in ${deviceIds}
	do
		props=$(xinput list-props $deviceId | grep "${1}" | grep -v "Default" | sed -n 's/.*(\([0-9]\+\)).*/\1/p')

		for prop in $props
		do
			xinput set-prop ${deviceId} "${1}" ${2}
		done 
	done
}

set_property "libinput Accel Profile Enabled" "0, 1"
set_property "libinput Accel Speed" "-0.4"