#!/bin/bash

if [[ "$(xinput | grep Touchpad | awk '{print $5}')" == "Touchpad" ]]
then
    TOUCHPAD_DEVICE_ID="$(xinput | grep Touchpad | awk '{print $3,$4,$5}')"

    xinput --set-prop "${TOUCHPAD_DEVICE_ID}" "libinput Tapping Enabled" 1
fi