#!/bin/bash

function set_property {

	#
	# https://askubuntu.com/questions/345355/xinput-list-shows-same-device-twice-device-ids-change-how-to-use-set-prop
	# https://stackoverflow.com/questions/18755967/how-to-make-a-program-that-finds-ids-of-xinput-devices-and-sets-xinput-some-set/18756948#18756948
	# https://wiki.archlinux.org/index.php/Mouse_acceleration
	#

	local deviceIds=$(xinput --list | grep "Logitech MX518\|Logitech USB Receiver" | sed -n 's/.*id=\([0-9]\+\).*/\1/p')

	for deviceId in ${deviceIds}
	do
		props=$(xinput list-props $deviceId | grep "${1}" | grep -v "Default" | sed -n 's/.*(\([0-9]\+\)).*/\1/p')

		for prop in $props
		do
			xinput set-prop ${deviceId} "${1}" ${2}
		done 
	done
}

set_property "libinput Accel Profile Enabled" "0, 1"
set_property "libinput Accel Speed" "-0.4"